### ISSUE TITLE
Should the input facts in the example be [1, 3, 224, 224]?

### ISSUE THREAD

**Issue by danielbank** [bminixhofer/tractjs#11]
I don't know much about the input facts but it seems like the standard referenced ones for the TensorFlow models is `[1, 224, 224, 3]` (see https://github.com/bminixhofer/tractjs/issues/5).  However the example in the README is `[1, 3, 224, 224]`.  More a question but if it is a typo, this issue could be for updating that.  In my own tinkering, I needed to use `[1, 224, 224, 3]`

**Comment by bminixhofer** [comment]
Tensorflow uses NHWC while ONNX uses NCHW. So it shouldn't necessarily be changed, but it should clarify that. Thanks for pointing that out, you get blind to those things after working on the project for a long time :)
