### ISSUE TITLE
What is the proper flow control for loading a model?

### ISSUE THREAD

**Issue by danielbank** [bminixhofer/tractjs#15]
When trying to detect when a model is loaded (or failed to load), I have written my code as follows:
```
const model: Model = new Model('./tests/plus3.pb');
await model.modelId;
```

In the course of writing the unit test PR, I am seeing that this raises a TypeScript error:
```
Property 'modelId' is private and only accessible within class 'Model'.
```

This raises the question for me, is there a more appropriate way for detecting when the model loads?  On the surface of it, this feels like a layer of indirection and it would be easier to do:
```
const model: Model = await new Model('./tests/plus3.pb');
```

If it is the most appropriate way, the `private` should be dropped from the `modelId` property.

**Comment by bminixhofer** [comment]
This is indeed a layer of indirection, but in Javascript a [constructor must always return the class it is constructing, it can not be asynchronous](https://stackoverflow.com/a/43433773).

Initially I thought that just waiting for the model load on the first call to `predict` would be enough; but I agree that in some cases you will want to know when the model is loaded before predicting, specifically to check whether loading was successful. Thanks for bringing that up!

Making `modelId` public is ugly; I could add a function `async loaded() -> Promise<void>` that resolves once the model is loaded or errs if there was an error loading the model. Does that sound good to you?

**Comment by danielbank** [comment]
I like the idea of the `loaded` function.  My mild opinion would be `async isLoaded() -> Promise<boolean>`, but anything that provides the ability to check is great.

**Comment by bminixhofer** [comment]
Fixed now, I stuck with returning a `Promise<void>` since a `Promise<bool>` would always resolve to `true` if it does resolve - if there's an error, it would have rejected anyway.
