### ISSUE TITLE
Move cypress to devDependencies

### ISSUE THREAD

**Issue by bard** [bminixhofer/tractjs#25]
On cursory look it seems to be used for tests only, but it's getting pulled into production builds (`yarn install --production`) because it's in package.json's `dependencies` instead of `devDependencies`.

(The package by itself isn't particularly heavy, but upon installation it downloads a zip that expands to 700+ MB in `~/.cache/Cypress` and inflates Docker images.)

**Comment by bminixhofer** [comment]
Good catch! I'll fix it.

**Comment by bminixhofer** [comment]
Just pushed a fix, if it passes CI I'll do a quick release.

**Comment by bminixhofer** [comment]
This is fixes in 0.3.4

**Comment by bard** [comment]
Thanks!
